name: pip_video_player_macos
description: MacOS implementation of the pip_video_player plugin
version: 0.1.0+1


environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: pip_video_player
    platforms:
      macos:
        pluginClass: PipVideoPlayerPlugin
        dartPluginClass: PipVideoPlayerMacOS

dependencies:
  flutter:
    sdk: flutter
  pip_video_player_platform_interface:
    path: ../pip_video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
