version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pip_video_player_windows"
    schedule:
      interval: "daily"