name: pip_video_player_platform_interface
description: A common platform interface for the pip_video_player plugin.
version: 0.1.0+1


environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
