name: pip_video_player
description: The PiP Video Player plugin is a versatile Flutter plugin designed to enable Picture in Picture (PiP) functionality across multiple platforms. Currently supporting Android and iOS, this plugin aims to extend its support to Windows, Linux, macOS, and Web, providing a seamless multimedia experience across all major platforms. With Picture in Picture, users can continue watching video content while interacting with other apps or even when the app is minimized or running in the background. This enhances user engagement and multitasking capabilities, making it an essential tool for modern multimedia applications.
version: 0.1.0+1


environment:
  sdk: ^3.4.0

flutter:
  plugin:
    platforms:
      android:
        default_package: pip_video_player_android
      ios:
        default_package: pip_video_player_ios
      linux:
        default_package: pip_video_player_linux
      macos:
        default_package: pip_video_player_macos
      web:
        default_package: pip_video_player_web
      windows:
        default_package: pip_video_player_windows

dependencies:
  flutter:
    sdk: flutter
  pip_video_player_android:
    path: ../pip_video_player_android
  pip_video_player_ios:
    path: ../pip_video_player_ios
  pip_video_player_linux:
    path: ../pip_video_player_linux
  pip_video_player_macos:
    path: ../pip_video_player_macos
  pip_video_player_platform_interface:
    path: ../pip_video_player_platform_interface
  pip_video_player_web:
    path: ../pip_video_player_web
  pip_video_player_windows:
    path: ../pip_video_player_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
