name: pip_video_player_ios
description: iOS implementation of the pip_video_player plugin
version: 0.1.0+1


environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: pip_video_player
    platforms:
      ios:
        pluginClass: PipVideoPlayerPlugin
        dartPluginClass: PipVideoPlayerIOS

dependencies:
  flutter:
    sdk: flutter
  pip_video_player_platform_interface:
    path: ../pip_video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
